### ISSUE TITLE
text annotation (highlighting) for pdfs?

### ISSUE THREAD

**Issue by sgibb** [LinusCDE/plato#1]
Thanks for porting plato to the remarkable. I often read scientific papers. It would be very great if it would be possible to use the pen to highlight text that would be stored as annotations in the pdf (as done by e.g. okular).

**Comment by LinusCDE** [comment]
Hi,
sadly I don't know much about pdf rendering. While I am interested in making some changes and additions to the software, I don't plan any major changes in the core functionality.

Plato uses [mupdf](https://mupdf.com/) for viewing pdfs. This is a c library that is only meant for viewing pdfs. Not modifying them. There may be some possibilities should the library offer Render Parts (e.g. text at positions instead of just an image), but I'm not sure of that at all.

Please request the feature [in the original project](baskerville/plato). Should they add such a major feature, I may very well port that over, too. (Depending on what success I have with some changes, I'll also attempt backport stuff there.).

Btw: If you want to destroy your productivity, I have put together some tetris game logic on the device [here](https://github.com/LinusCDE/retris) (wip). Not really nice to play and currently lacks gestures, but at least the device now has some game on it.
