### ISSUE TITLE
Settings changes on plato.toml aren’t persistent

### ISSUE THREAD

**Issue by pheraph** [LinusCDE/plato#15]
In #7 my question was also raised, but since the problem there was different, I created a new issue. Even after spending quite some time, I have not been able to get my changes to the `/opt/etc/plato.toml` file to persist. I understand this file is a symlink to `/opt/etc/settings.toml` and I am using the latest plato version from the Toltec testing branch together with remux. If I - as suggested - explicitly quit/kill plato before editing or do a reboot before, the file is still reset while/after the next invocation of Plato. I even completely removed all installation files, reinstalled Plato, manually duplicated the settings-sample.toml to the correct location and made my changes. On the first launch of Plato these changes were applied and visible in Plato (I added another library location and could select it). But when I launched Plato again the settings file was overwritten and my changes were wiped out. 

So my simple question is: how exactly can I make persistent changes to the settings file?

**Comment by ralsei** [comment]
Deleting `plato.toml`'s contents and running it, only changing what I deem necessary, seems to work. So there's something in the file that causes it to error out.

**Comment by LinusCDE** [comment]
Hi. Sorry for my late response. I somehow missed the creation of this issue. I updated my email filters, so this shouldn't happen anymore.

> I understand this file is a symlink to /opt/etc/settings.toml and I am using the latest plato version from the Toltec testing branch together with remux.

It is indeed a symlink. But it is reversed where `/opt/lib/plato/Settings.toml` links to `/opt/etc/plato.toml`. Just a minor nitpick and it probably doesn't matter here. I basically put the standalone installation into `/opt/lib/plato` and created symlinks were needed. So plato will try to create the file `Settings.toml` in its workdir (which is `/opt/lib/plato`). Since it's a symlink, the file will be created at `/opt/etc/plato.toml` instead. A dead symlinks (target file not existing) simply appears to be a non-existing file if a program doesn't check whether there is actually s symlink.

I'm not sure why your settings don't persist in this case. @ralsei's answer might help as well.

I'm not entirely sure rn, but plato might overwrite the file with the default content when the file is "faulty" (wrong types or missing entries). Unknown entries are not faulty but simply ignored and forgotten/not written when saving.

Plato also only ever writes the file when it is properly quit. This might also be the reason it discards your changes. If it isn't because of any error then, quitting plato after you changed the file will trigger plato to actually overwrite your file with it's current state. So it's best to ensure plato is not running while doing the modifications.

Errors might also pop up in the logs (stdout/stderr). For remux, run `journalctl -fu remux` to get a live feed of the output (remove the `f` to only view the existing log and navigate in a `less`-like style in it.

**Comment by ralsei** [comment]
Minimum reproducible example for me is:
- remove everything in `/opt/etc/plato.toml` or `/opt/lib/plato/Settings.toml` (symlinked) and add something simple, like just `time-format = "%I:%M"`
- open Plato from the command line
- Settings are read fine, 12-hour time is displayed in status-bar
- properly quit Plato
- Settings are saved to file, `time-format = "%I:%M"` is still in the file, along with all the newly added defaults
- open Plato from the command line, fails to parse TOML, 24-hour time is shown in status-bar

**Comment by LinusCDE** [comment]
I think your installed plato really still had this bug in it. Your version should be 0.9.13 (release 7) as seen [here](https://github.com/toltec-dev/toltec/blob/stable/package/plato/package#L8-L16). And the commit that I believe fixed the issues for good was part of release 8 and ongoing but not release 7 as seen in the tags on [this commit](https://github.com/LinusCDE/plato/commit/4e720aae7f3e9e588f62317a179f522a6aa8cdf0).

**Comment by ralsei** [comment]
Updating to 0.9.17 on Toltec testing gives the error
```
Can't load settings: can't parse TOML content from Settings.toml: missing field `ignored-buttons` for key `remarkable` at line 95 column 1.
```

**Comment by LinusCDE** [comment]
> Updating to 0.9.17 on Toltec testing gives the error
> 
> ```
> Can't load settings: can't parse TOML content from Settings.toml: missing field `ignored-buttons` for key `remarkable` at line 95 column 1.
> ```
> 
> Adding just `ignored-buttons = []` works, but `plato.toml` gets overwritten _again_, removing this field, and then it fails to parse.

Thanks! I didn't catch this bug. Will try to add a fix the coming week!

**Comment by pheraph** [comment]
Thank you very much for the insightful discussion. I can now reproduce the problem as well. My additions to Settings.toml are only accepted if they are added above the [[remarkable]] block:

```
.... added code ....

[[remarkable]]
```

If the changes are after the [[remarkable]] block, they are ignored as long as the following entry has not been added manually:

```
[[remarkable]]
ignored-buttons = []
```

With this added entry my changes are accepted and used, but only until I quit Plato with the Quit-menu. After that the entry ignored-buttons = [] is missing again. The manual entries seem to be preserved though.

**Comment by LinusCDE** [comment]
Just checked it on the newest version and plato seems to handle missing entries well. When I have a config like

```toml
# ...

[remarkable]
refresh-quality = "normal"
#input-sources = ["touch", "pen"] # This entry will be missing

[[libraries]]
name = "Mediaa" # Modified
path = "media"
mode = "database"
sort-method = "opened"
first-column = "title-and-author"
second-column = "progress"
thumbnail-previews = true

# ...
```

and start plato, the config will be read and saving adds the commented out line while also preserving my change.

I think the issue is that it can't deal with an empty list for `input-sources` and views it as non-existing, yet cannot add a default for that (probably something to do with how the parser deals with it by default).

With `input-sources = []`, plato prints the following error: ```Can't load settings: can't parse TOML content from Settings.toml: missing field `ignored-buttons` for key `remarkable` at line 95 column 1.```

It seems to then just use the default values for everything instead and on quitting saves this new default config, which discards all changes.

So for the time being, removing the line completely is better than to keep it empty. An empty list would be harmful anyways since it would mean that the interface couldn't be interacted with (neither touch nor pen enabled).

---

Also a little aside on toml:

Using a `[something]` actually puts all the following entries into that as a category. So the first entries before any such section a considered global and each new section replaces the last one. Using `[[something]]` actually makes it a list. Each new entries is a new list entry for `something` in that case and a different type from `[something]`.

The `[remarkable]` section was added by me for custom settings for the device and is not supposed to be a list. So using `[[remarkable]]` instead of the former is actually a non-parsable config as well and will revert it to the default one. It prints this error in that case:

```Can't load settings: can't parse TOML content from Settings.toml: enum table must contain exactly one table for key `remarkable` at line 1 column 1.``` (the stated line seems wrong btw).

**Comment by LinusCDE** [comment]
I did some changes to the de-serialization of the `Settings.toml` (aka `plato.toml`) with commit 8a71b64f081896707865dbb4391cbd9590492b9c. It should now correctly load on missing entries and also change a `input-sources = []` to `input-sources = ["touch", "pen"]` by default with the following warning: ```WARN: remarkable input-sources is empty. Changed to default to prevent a unusable GUI.```.

It seems that an empty `input-sources` somehow led to serde recognizing the usually missing `ingored-buttons` as a problem and then resetting the config because of that. This should be solved.

I'll look to make this a release the coming days.

If you want to test it out now, I added the new binary in the attached zip file. Put the file from the zip on the remarkable as `/opt/lib/plato/plato` when using toltec or as `plato` in your standalone folder. Not sure if it might cause render issues with some launchers. You can revert the binary by removing the plato package and reinstalling it (`opkg remove plato && opkg install plato`). It will not delete your config or data.

[plato.zip](https://github.com/LinusCDE/plato/files/6648894/plato.zip)

**Comment by ralsei** [comment]
Confirmed working on rM1, software 2.7, with remux. Thanks!
