### ISSUE TITLE
```margin-with``` over 10 is ignored

### ISSUE THREAD

**Issue by fmrtn** [LinusCDE/plato#22]
I can set any number of margins in Settings.toml, but nothing above 10.

```
margin-width = 15
min-margin-width = 10
max-margin-width = 20
```

**Comment by EnderKill98** [comment]
Sorry for the late answer, have not gotten around to testing until yet. Could confirm the bug. Will do some testing on the newest version to make sure it's not an outdated bug. Otherwise it's probably an issue that is best solved by [upstream plato](https://github.com/baskerville/plato).

**Comment by LinusCDE** [comment]
Hi. Sorry for the very late answer. I tested and confirmed the bug. I did a peak the related source a few days back and couldn't find an obvious cap there. Will need to test it on the newest version. I would assume it's a issue that is better suited for [upstream plato](https://github.com/baskerville/plato) then.

**Comment by LinusCDE** [comment]
Tested it on both Plato 0.9.25 and 0.9.34 and both were unable to set higher margins of 15 or 20 even when setting the min-margin-with to it as well.

I looked over the code again and have found the issue. The check `margin.with <= 10` on line 129 in [`crates/core/src/document/html/engine.rs`](https://github.com/LinusCDE/plato/blob/master/crates/core/src/document/html/engine.rs) is responsible for this limitation:

https://github.com/LinusCDE/plato/blob/43753bfefa6c5f2631d901609e62799d2b8a2ce5/crates/core/src/document/html/engine.rs#L128-L132

I tested the change out and it seems to work. Below are two screenshots where I set `margin-width` to `30` (seems that `margin-with-max` doesn't limit this):

<img src="https://user-images.githubusercontent.com/22298664/228853818-7f970922-8386-4593-b675-c74dfa684342.png" width="45%"> <img src="https://user-images.githubusercontent.com/22298664/228853899-b87e2e87-9f2f-421a-9d97-f0fdc50c0f12.png" width="45%">

Here is a release of the currently latest version (plato 0.9.34 for remarkable) with the offending check removed, which allows to set greater margins: [plato-0.9.34-rm-release-13-issue-22-patch.tar.gz](https://github.com/LinusCDE/plato/files/11112204/plato-0.9.34-rm-release-13-issue-22-patch.tar.gz) (If you already run the latest release - not yet published on toltec due to dependency issues - you can simple replace the plato binary at `/var/lib/plato/plato`. Otherwise i recommend that you extract it somewhere and add a way to run the starter shell script `plato.sh`. You can simply replace the `media` folder by a link to your used one using `cd /path/to/extracted/archive && rm -rf media && ln -s /home/root/plato-media media`.)


The best way is probably to open an issue on upstream plato regarding this, as this change is nothing remarkable specific imo and should be discussed there. Either it was just a good limit assumed when added or there was a reason for it that I'm not aware of.

So feel free to open the issue here: https://github.com/baskerville/plato/issues
With this comment, the cause is now known, so the content should probably be to ask whether it can be increased. The main dev there will most likely know if there is a problem with that. Feel free to reference this comment.

**Comment by fmrtn** [comment]
It works.

I just replaced the binary (I was using 0.9.34) and now works fine. Thanks you for that.

I'm not sure if this is correct but my installation is in `/opt/lib/plato/` and not in `/var/lib/plato/`.

**Comment by LinusCDE** [comment]
> I just replaced the binary (I was using 0.9.34) and now works fine. Thanks you for that.

Nice to hear. :smile: 
> I'm not sure if this is correct but my installation is in /opt/lib/plato/ and not in /var/lib/plato/.

That is probably correct. I just wrote that path out of memory. Your's is actually the correct one I meant to name.
