### ISSUE TITLE
After pressing Calculator rM1 froze :/ What should I do?

### ISSUE THREAD

**Issue by lleonora** [LinusCDE/plato#8]
Dear Developer! Thank you very much for this great thing! I love Plato very much, but when trying different features, I managed to make it freeze. How can I unfreeze my rM? The ssh didn't interrupt, so I can type something from the computer. Also on terminal it wrote "Error: Permission denied (os error 13)" - don't know when, but probably it's a Calculator error.

**Comment by LinusCDE** [comment]
Hi lleonor,

first thanks that you enjoy it. I actually only ported this software to the reMarkable. baskerville is the creator of this amazing piece of software (cc @baskerville).

> The ssh didn't interrupt, so I can type something from the computer. Also on terminal it wrote "Error: Permission denied (os error 13)" - don't know when, but probably it's a Calculator error.

By "The ssh didn't interrupt" I guess that the error you spotted, made the application crash. In that case you'll see the last image on the eink making it seem like a freeze. I'm not really sure what caused it. The device runs as root, so a permission denied error usually implies a reject from some driver or attempting to run a executable that is not marked as such.

On my rM 1, the calculator seems to run fine. I would guess that the process of me porting it caused the issue that is most likely not present on officially supported Kobo device. May I ask how you installed Plato? Did you used the standalone or toltec version (if toltec, which branch) otherwise which version, ...?

It's pretty late for me rn and tomorrow will be a busy day. So I'll apologize in advance if it will take me about 24-36 hours before I respond again.

**Comment by lleonora** [comment]
Dear Linus, thank you very much for your reply! It helped, now it works :)
At first I didn't understand that I should've unpacked the archive on the rM itself, but by saying "attempting to run a executable that is not marked as such" you brought my attention to that. Reinstalled the standalone verison, unpacked properly, everything is perfect!
I'm very sorry for disturbing you for such stupid reason :/ But I'm a newbie, don't know where else to seek help.
Thanks!

**Comment by LinusCDE** [comment]
No problem. Always glad to help. Linux has some pretty generic and confusing errors tbh. Some of them get even pretty experienced users. :smile:
